// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/digitalocean/godo (interfaces: AgentPlatformService)
//
// Generated by this command:
//
//	mockgen -destination=./mocks.go -package inferencemodelcatalog github.com/digitalocean/godo AgentPlatformService
//

// Package inferencemodelcatalog is a generated GoMock package.
package inferencemodelcatalog

import (
	context "context"
	reflect "reflect"

	godo "github.com/digitalocean/godo"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentPlatformService is a mock of AgentPlatformService interface.
type MockAgentPlatformService struct {
	ctrl     *gomock.Controller
	recorder *MockAgentPlatformServiceMockRecorder
	isgomock struct{}
}

// MockAgentPlatformServiceMockRecorder is the mock recorder for MockAgentPlatformService.
type MockAgentPlatformServiceMockRecorder struct {
	mock *MockAgentPlatformService
}

// NewMockAgentPlatformService creates a new mock instance.
func NewMockAgentPlatformService(ctrl *gomock.Controller) *MockAgentPlatformService {
	mock := &MockAgentPlatformService{ctrl: ctrl}
	mock.recorder = &MockAgentPlatformServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentPlatformService) EXPECT() *MockAgentPlatformServiceMockRecorder {
	return m.recorder
}

// AddAgentRoute mocks base method.
func (m *MockAgentPlatformService) AddAgentRoute(arg0 context.Context, arg1, arg2 string, arg3 *godo.AgentRouteCreateRequest) (*godo.AgentRouteResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAgentRoute", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*godo.AgentRouteResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddAgentRoute indicates an expected call of AddAgentRoute.
func (mr *MockAgentPlatformServiceMockRecorder) AddAgentRoute(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAgentRoute", reflect.TypeOf((*MockAgentPlatformService)(nil).AddAgentRoute), arg0, arg1, arg2, arg3)
}

// AddKnowledgeBaseDataSource mocks base method.
func (m *MockAgentPlatformService) AddKnowledgeBaseDataSource(ctx context.Context, knowledgeBaseID string, addDataSource *godo.AddKnowledgeBaseDataSourceRequest) (*godo.KnowledgeBaseDataSource, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddKnowledgeBaseDataSource", ctx, knowledgeBaseID, addDataSource)
	ret0, _ := ret[0].(*godo.KnowledgeBaseDataSource)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddKnowledgeBaseDataSource indicates an expected call of AddKnowledgeBaseDataSource.
func (mr *MockAgentPlatformServiceMockRecorder) AddKnowledgeBaseDataSource(ctx, knowledgeBaseID, addDataSource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddKnowledgeBaseDataSource", reflect.TypeOf((*MockAgentPlatformService)(nil).AddKnowledgeBaseDataSource), ctx, knowledgeBaseID, addDataSource)
}

// AttachKnowledgeBaseToAgent mocks base method.
func (m *MockAgentPlatformService) AttachKnowledgeBaseToAgent(ctx context.Context, agentID, knowledgeBaseID string) (*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachKnowledgeBaseToAgent", ctx, agentID, knowledgeBaseID)
	ret0, _ := ret[0].(*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AttachKnowledgeBaseToAgent indicates an expected call of AttachKnowledgeBaseToAgent.
func (mr *MockAgentPlatformServiceMockRecorder) AttachKnowledgeBaseToAgent(ctx, agentID, knowledgeBaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachKnowledgeBaseToAgent", reflect.TypeOf((*MockAgentPlatformService)(nil).AttachKnowledgeBaseToAgent), ctx, agentID, knowledgeBaseID)
}

// CancelIndexingJob mocks base method.
func (m *MockAgentPlatformService) CancelIndexingJob(ctx context.Context, indexingJobUUID string) (*godo.IndexingJobResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelIndexingJob", ctx, indexingJobUUID)
	ret0, _ := ret[0].(*godo.IndexingJobResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CancelIndexingJob indicates an expected call of CancelIndexingJob.
func (mr *MockAgentPlatformServiceMockRecorder) CancelIndexingJob(ctx, indexingJobUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelIndexingJob", reflect.TypeOf((*MockAgentPlatformService)(nil).CancelIndexingJob), ctx, indexingJobUUID)
}

// CancelModelEvaluationRun mocks base method.
func (m *MockAgentPlatformService) CancelModelEvaluationRun(ctx context.Context, evalRunUUID string) (*godo.ModelEvaluationRunCancelResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelModelEvaluationRun", ctx, evalRunUUID)
	ret0, _ := ret[0].(*godo.ModelEvaluationRunCancelResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CancelModelEvaluationRun indicates an expected call of CancelModelEvaluationRun.
func (mr *MockAgentPlatformServiceMockRecorder) CancelModelEvaluationRun(ctx, evalRunUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelModelEvaluationRun", reflect.TypeOf((*MockAgentPlatformService)(nil).CancelModelEvaluationRun), ctx, evalRunUUID)
}

// CancelSimulationRun mocks base method.
func (m *MockAgentPlatformService) CancelSimulationRun(ctx context.Context, runUUID string) (*godo.SimulationRun, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelSimulationRun", ctx, runUUID)
	ret0, _ := ret[0].(*godo.SimulationRun)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CancelSimulationRun indicates an expected call of CancelSimulationRun.
func (mr *MockAgentPlatformServiceMockRecorder) CancelSimulationRun(ctx, runUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelSimulationRun", reflect.TypeOf((*MockAgentPlatformService)(nil).CancelSimulationRun), ctx, runUUID)
}

// CreateAgent mocks base method.
func (m *MockAgentPlatformService) CreateAgent(arg0 context.Context, arg1 *godo.AgentCreateRequest) (*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAgent", arg0, arg1)
	ret0, _ := ret[0].(*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateAgent indicates an expected call of CreateAgent.
func (mr *MockAgentPlatformServiceMockRecorder) CreateAgent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAgent", reflect.TypeOf((*MockAgentPlatformService)(nil).CreateAgent), arg0, arg1)
}

// CreateAgentAPIKey mocks base method.
func (m *MockAgentPlatformService) CreateAgentAPIKey(arg0 context.Context, arg1 string, arg2 *godo.AgentAPIKeyCreateRequest) (*godo.ApiKeyInfo, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAgentAPIKey", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.ApiKeyInfo)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateAgentAPIKey indicates an expected call of CreateAgentAPIKey.
func (mr *MockAgentPlatformServiceMockRecorder) CreateAgentAPIKey(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAgentAPIKey", reflect.TypeOf((*MockAgentPlatformService)(nil).CreateAgentAPIKey), arg0, arg1, arg2)
}

// CreateAnthropicAPIKey mocks base method.
func (m *MockAgentPlatformService) CreateAnthropicAPIKey(ctx context.Context, anthropicAPIKeyCreateRequest *godo.AnthropicAPIKeyCreateRequest) (*godo.AnthropicApiKeyInfo, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAnthropicAPIKey", ctx, anthropicAPIKeyCreateRequest)
	ret0, _ := ret[0].(*godo.AnthropicApiKeyInfo)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateAnthropicAPIKey indicates an expected call of CreateAnthropicAPIKey.
func (mr *MockAgentPlatformServiceMockRecorder) CreateAnthropicAPIKey(ctx, anthropicAPIKeyCreateRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAnthropicAPIKey", reflect.TypeOf((*MockAgentPlatformService)(nil).CreateAnthropicAPIKey), ctx, anthropicAPIKeyCreateRequest)
}

// CreateCustomEvaluationMetric mocks base method.
func (m *MockAgentPlatformService) CreateCustomEvaluationMetric(ctx context.Context, createRequest *godo.CreateCustomEvaluationMetricRequest) (*godo.EvaluationMetric, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomEvaluationMetric", ctx, createRequest)
	ret0, _ := ret[0].(*godo.EvaluationMetric)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateCustomEvaluationMetric indicates an expected call of CreateCustomEvaluationMetric.
func (mr *MockAgentPlatformServiceMockRecorder) CreateCustomEvaluationMetric(ctx, createRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomEvaluationMetric", reflect.TypeOf((*MockAgentPlatformService)(nil).CreateCustomEvaluationMetric), ctx, createRequest)
}

// CreateEvaluationDataset mocks base method.
func (m *MockAgentPlatformService) CreateEvaluationDataset(ctx context.Context, createRequest *godo.CreateEvaluationDatasetRequest) (*godo.CreateEvaluationDatasetResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvaluationDataset", ctx, createRequest)
	ret0, _ := ret[0].(*godo.CreateEvaluationDatasetResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateEvaluationDataset indicates an expected call of CreateEvaluationDataset.
func (mr *MockAgentPlatformServiceMockRecorder) CreateEvaluationDataset(ctx, createRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvaluationDataset", reflect.TypeOf((*MockAgentPlatformService)(nil).CreateEvaluationDataset), ctx, createRequest)
}

// CreateFunctionRoute mocks base method.
func (m *MockAgentPlatformService) CreateFunctionRoute(arg0 context.Context, arg1 string, arg2 *godo.FunctionRouteCreateRequest) (*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFunctionRoute", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateFunctionRoute indicates an expected call of CreateFunctionRoute.
func (mr *MockAgentPlatformServiceMockRecorder) CreateFunctionRoute(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFunctionRoute", reflect.TypeOf((*MockAgentPlatformService)(nil).CreateFunctionRoute), arg0, arg1, arg2)
}

// CreateInferenceRouter mocks base method.
func (m *MockAgentPlatformService) CreateInferenceRouter(arg0 context.Context, arg1 *godo.InferenceRouterCreateRequest) (*godo.InferenceRouter, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInferenceRouter", arg0, arg1)
	ret0, _ := ret[0].(*godo.InferenceRouter)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateInferenceRouter indicates an expected call of CreateInferenceRouter.
func (mr *MockAgentPlatformServiceMockRecorder) CreateInferenceRouter(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInferenceRouter", reflect.TypeOf((*MockAgentPlatformService)(nil).CreateInferenceRouter), arg0, arg1)
}

// CreateKnowledgeBase mocks base method.
func (m *MockAgentPlatformService) CreateKnowledgeBase(ctx context.Context, knowledgeBaseCreate *godo.KnowledgeBaseCreateRequest) (*godo.KnowledgeBase, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKnowledgeBase", ctx, knowledgeBaseCreate)
	ret0, _ := ret[0].(*godo.KnowledgeBase)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateKnowledgeBase indicates an expected call of CreateKnowledgeBase.
func (mr *MockAgentPlatformServiceMockRecorder) CreateKnowledgeBase(ctx, knowledgeBaseCreate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKnowledgeBase", reflect.TypeOf((*MockAgentPlatformService)(nil).CreateKnowledgeBase), ctx, knowledgeBaseCreate)
}

// CreateModelEvalDatasetUploadPresignedURLs mocks base method.
func (m *MockAgentPlatformService) CreateModelEvalDatasetUploadPresignedURLs(ctx context.Context, createRequest *godo.CreateModelEvalDatasetUploadPresignedURLsRequest) (*godo.CreateModelEvalDatasetUploadPresignedURLsResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateModelEvalDatasetUploadPresignedURLs", ctx, createRequest)
	ret0, _ := ret[0].(*godo.CreateModelEvalDatasetUploadPresignedURLsResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateModelEvalDatasetUploadPresignedURLs indicates an expected call of CreateModelEvalDatasetUploadPresignedURLs.
func (mr *MockAgentPlatformServiceMockRecorder) CreateModelEvalDatasetUploadPresignedURLs(ctx, createRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateModelEvalDatasetUploadPresignedURLs", reflect.TypeOf((*MockAgentPlatformService)(nil).CreateModelEvalDatasetUploadPresignedURLs), ctx, createRequest)
}

// CreateModelEvaluationRun mocks base method.
func (m *MockAgentPlatformService) CreateModelEvaluationRun(ctx context.Context, createRequest *godo.CreateModelEvaluationRunRequest) (*godo.ModelEvaluationRunCreateResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateModelEvaluationRun", ctx, createRequest)
	ret0, _ := ret[0].(*godo.ModelEvaluationRunCreateResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateModelEvaluationRun indicates an expected call of CreateModelEvaluationRun.
func (mr *MockAgentPlatformServiceMockRecorder) CreateModelEvaluationRun(ctx, createRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateModelEvaluationRun", reflect.TypeOf((*MockAgentPlatformService)(nil).CreateModelEvaluationRun), ctx, createRequest)
}

// CreateOpenAIAPIKey mocks base method.
func (m *MockAgentPlatformService) CreateOpenAIAPIKey(ctx context.Context, openaiAPIKeyCreate *godo.OpenAIAPIKeyCreateRequest) (*godo.OpenAiApiKey, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOpenAIAPIKey", ctx, openaiAPIKeyCreate)
	ret0, _ := ret[0].(*godo.OpenAiApiKey)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateOpenAIAPIKey indicates an expected call of CreateOpenAIAPIKey.
func (mr *MockAgentPlatformServiceMockRecorder) CreateOpenAIAPIKey(ctx, openaiAPIKeyCreate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOpenAIAPIKey", reflect.TypeOf((*MockAgentPlatformService)(nil).CreateOpenAIAPIKey), ctx, openaiAPIKeyCreate)
}

// CreateScenarioSet mocks base method.
func (m *MockAgentPlatformService) CreateScenarioSet(ctx context.Context, createRequest *godo.CreateScenarioSetRequest) (*godo.ScenarioSet, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScenarioSet", ctx, createRequest)
	ret0, _ := ret[0].(*godo.ScenarioSet)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateScenarioSet indicates an expected call of CreateScenarioSet.
func (mr *MockAgentPlatformServiceMockRecorder) CreateScenarioSet(ctx, createRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScenarioSet", reflect.TypeOf((*MockAgentPlatformService)(nil).CreateScenarioSet), ctx, createRequest)
}

// CreateScenarioSetFromLibrary mocks base method.
func (m *MockAgentPlatformService) CreateScenarioSetFromLibrary(ctx context.Context, libraryScenarioUUID string, createRequest *godo.CreateScenarioSetFromLibraryRequest) (*godo.ScenarioSet, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScenarioSetFromLibrary", ctx, libraryScenarioUUID, createRequest)
	ret0, _ := ret[0].(*godo.ScenarioSet)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateScenarioSetFromLibrary indicates an expected call of CreateScenarioSetFromLibrary.
func (mr *MockAgentPlatformServiceMockRecorder) CreateScenarioSetFromLibrary(ctx, libraryScenarioUUID, createRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScenarioSetFromLibrary", reflect.TypeOf((*MockAgentPlatformService)(nil).CreateScenarioSetFromLibrary), ctx, libraryScenarioUUID, createRequest)
}

// CreateScenarioSetUploadPresignedURLs mocks base method.
func (m *MockAgentPlatformService) CreateScenarioSetUploadPresignedURLs(ctx context.Context, createRequest *godo.CreateScenarioSetUploadPresignedURLsRequest) (*godo.CreateScenarioSetUploadPresignedURLsResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScenarioSetUploadPresignedURLs", ctx, createRequest)
	ret0, _ := ret[0].(*godo.CreateScenarioSetUploadPresignedURLsResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateScenarioSetUploadPresignedURLs indicates an expected call of CreateScenarioSetUploadPresignedURLs.
func (mr *MockAgentPlatformServiceMockRecorder) CreateScenarioSetUploadPresignedURLs(ctx, createRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScenarioSetUploadPresignedURLs", reflect.TypeOf((*MockAgentPlatformService)(nil).CreateScenarioSetUploadPresignedURLs), ctx, createRequest)
}

// CreateSimulationRun mocks base method.
func (m *MockAgentPlatformService) CreateSimulationRun(ctx context.Context, createRequest *godo.CreateSimulationRunRequest) (*godo.SimulationRun, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSimulationRun", ctx, createRequest)
	ret0, _ := ret[0].(*godo.SimulationRun)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateSimulationRun indicates an expected call of CreateSimulationRun.
func (mr *MockAgentPlatformServiceMockRecorder) CreateSimulationRun(ctx, createRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSimulationRun", reflect.TypeOf((*MockAgentPlatformService)(nil).CreateSimulationRun), ctx, createRequest)
}

// DeleteAgent mocks base method.
func (m *MockAgentPlatformService) DeleteAgent(arg0 context.Context, arg1 string) (*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAgent", arg0, arg1)
	ret0, _ := ret[0].(*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteAgent indicates an expected call of DeleteAgent.
func (mr *MockAgentPlatformServiceMockRecorder) DeleteAgent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAgent", reflect.TypeOf((*MockAgentPlatformService)(nil).DeleteAgent), arg0, arg1)
}

// DeleteAgentAPIKey mocks base method.
func (m *MockAgentPlatformService) DeleteAgentAPIKey(arg0 context.Context, arg1, arg2 string) (*godo.ApiKeyInfo, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAgentAPIKey", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.ApiKeyInfo)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteAgentAPIKey indicates an expected call of DeleteAgentAPIKey.
func (mr *MockAgentPlatformServiceMockRecorder) DeleteAgentAPIKey(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAgentAPIKey", reflect.TypeOf((*MockAgentPlatformService)(nil).DeleteAgentAPIKey), arg0, arg1, arg2)
}

// DeleteAgentRoute mocks base method.
func (m *MockAgentPlatformService) DeleteAgentRoute(arg0 context.Context, arg1, arg2 string) (*godo.AgentRouteResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAgentRoute", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.AgentRouteResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteAgentRoute indicates an expected call of DeleteAgentRoute.
func (mr *MockAgentPlatformServiceMockRecorder) DeleteAgentRoute(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAgentRoute", reflect.TypeOf((*MockAgentPlatformService)(nil).DeleteAgentRoute), arg0, arg1, arg2)
}

// DeleteAnthropicAPIKey mocks base method.
func (m *MockAgentPlatformService) DeleteAnthropicAPIKey(ctx context.Context, id string) (*godo.AnthropicApiKeyInfo, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAnthropicAPIKey", ctx, id)
	ret0, _ := ret[0].(*godo.AnthropicApiKeyInfo)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteAnthropicAPIKey indicates an expected call of DeleteAnthropicAPIKey.
func (mr *MockAgentPlatformServiceMockRecorder) DeleteAnthropicAPIKey(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAnthropicAPIKey", reflect.TypeOf((*MockAgentPlatformService)(nil).DeleteAnthropicAPIKey), ctx, id)
}

// DeleteCustomEvaluationMetric mocks base method.
func (m *MockAgentPlatformService) DeleteCustomEvaluationMetric(ctx context.Context, metricUUID string) (*godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomEvaluationMetric", ctx, metricUUID)
	ret0, _ := ret[0].(*godo.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCustomEvaluationMetric indicates an expected call of DeleteCustomEvaluationMetric.
func (mr *MockAgentPlatformServiceMockRecorder) DeleteCustomEvaluationMetric(ctx, metricUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomEvaluationMetric", reflect.TypeOf((*MockAgentPlatformService)(nil).DeleteCustomEvaluationMetric), ctx, metricUUID)
}

// DeleteCustomModel mocks base method.
func (m *MockAgentPlatformService) DeleteCustomModel(ctx context.Context, uuid string) (*godo.CustomModelDeleteResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomModel", ctx, uuid)
	ret0, _ := ret[0].(*godo.CustomModelDeleteResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteCustomModel indicates an expected call of DeleteCustomModel.
func (mr *MockAgentPlatformServiceMockRecorder) DeleteCustomModel(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomModel", reflect.TypeOf((*MockAgentPlatformService)(nil).DeleteCustomModel), ctx, uuid)
}

// DeleteEvaluationDataset mocks base method.
func (m *MockAgentPlatformService) DeleteEvaluationDataset(ctx context.Context, datasetUUID string) (*godo.EvaluationDatasetDeleteResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEvaluationDataset", ctx, datasetUUID)
	ret0, _ := ret[0].(*godo.EvaluationDatasetDeleteResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteEvaluationDataset indicates an expected call of DeleteEvaluationDataset.
func (mr *MockAgentPlatformServiceMockRecorder) DeleteEvaluationDataset(ctx, datasetUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEvaluationDataset", reflect.TypeOf((*MockAgentPlatformService)(nil).DeleteEvaluationDataset), ctx, datasetUUID)
}

// DeleteFunctionRoute mocks base method.
func (m *MockAgentPlatformService) DeleteFunctionRoute(arg0 context.Context, arg1, arg2 string) (*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFunctionRoute", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteFunctionRoute indicates an expected call of DeleteFunctionRoute.
func (mr *MockAgentPlatformServiceMockRecorder) DeleteFunctionRoute(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFunctionRoute", reflect.TypeOf((*MockAgentPlatformService)(nil).DeleteFunctionRoute), arg0, arg1, arg2)
}

// DeleteInferenceRouter mocks base method.
func (m *MockAgentPlatformService) DeleteInferenceRouter(arg0 context.Context, arg1 string) (*godo.InferenceRouterDeleteResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInferenceRouter", arg0, arg1)
	ret0, _ := ret[0].(*godo.InferenceRouterDeleteResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteInferenceRouter indicates an expected call of DeleteInferenceRouter.
func (mr *MockAgentPlatformServiceMockRecorder) DeleteInferenceRouter(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInferenceRouter", reflect.TypeOf((*MockAgentPlatformService)(nil).DeleteInferenceRouter), arg0, arg1)
}

// DeleteKnowledgeBase mocks base method.
func (m *MockAgentPlatformService) DeleteKnowledgeBase(ctx context.Context, knowledgeBaseID string) (string, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKnowledgeBase", ctx, knowledgeBaseID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteKnowledgeBase indicates an expected call of DeleteKnowledgeBase.
func (mr *MockAgentPlatformServiceMockRecorder) DeleteKnowledgeBase(ctx, knowledgeBaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKnowledgeBase", reflect.TypeOf((*MockAgentPlatformService)(nil).DeleteKnowledgeBase), ctx, knowledgeBaseID)
}

// DeleteKnowledgeBaseDataSource mocks base method.
func (m *MockAgentPlatformService) DeleteKnowledgeBaseDataSource(ctx context.Context, knowledgeBaseID, dataSourceID string) (string, string, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKnowledgeBaseDataSource", ctx, knowledgeBaseID, dataSourceID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(*godo.Response)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// DeleteKnowledgeBaseDataSource indicates an expected call of DeleteKnowledgeBaseDataSource.
func (mr *MockAgentPlatformServiceMockRecorder) DeleteKnowledgeBaseDataSource(ctx, knowledgeBaseID, dataSourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKnowledgeBaseDataSource", reflect.TypeOf((*MockAgentPlatformService)(nil).DeleteKnowledgeBaseDataSource), ctx, knowledgeBaseID, dataSourceID)
}

// DeleteModelEvaluationPreset mocks base method.
func (m *MockAgentPlatformService) DeleteModelEvaluationPreset(ctx context.Context, evalPresetUUID string) (*godo.ModelEvaluationPresetDeleteResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteModelEvaluationPreset", ctx, evalPresetUUID)
	ret0, _ := ret[0].(*godo.ModelEvaluationPresetDeleteResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteModelEvaluationPreset indicates an expected call of DeleteModelEvaluationPreset.
func (mr *MockAgentPlatformServiceMockRecorder) DeleteModelEvaluationPreset(ctx, evalPresetUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteModelEvaluationPreset", reflect.TypeOf((*MockAgentPlatformService)(nil).DeleteModelEvaluationPreset), ctx, evalPresetUUID)
}

// DeleteModelEvaluationRun mocks base method.
func (m *MockAgentPlatformService) DeleteModelEvaluationRun(ctx context.Context, evalRunUUID string) (*godo.ModelEvaluationRunDeleteResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteModelEvaluationRun", ctx, evalRunUUID)
	ret0, _ := ret[0].(*godo.ModelEvaluationRunDeleteResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteModelEvaluationRun indicates an expected call of DeleteModelEvaluationRun.
func (mr *MockAgentPlatformServiceMockRecorder) DeleteModelEvaluationRun(ctx, evalRunUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteModelEvaluationRun", reflect.TypeOf((*MockAgentPlatformService)(nil).DeleteModelEvaluationRun), ctx, evalRunUUID)
}

// DeleteOpenAIAPIKey mocks base method.
func (m *MockAgentPlatformService) DeleteOpenAIAPIKey(ctx context.Context, openaiApiKeyId string) (*godo.OpenAiApiKey, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOpenAIAPIKey", ctx, openaiApiKeyId)
	ret0, _ := ret[0].(*godo.OpenAiApiKey)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteOpenAIAPIKey indicates an expected call of DeleteOpenAIAPIKey.
func (mr *MockAgentPlatformServiceMockRecorder) DeleteOpenAIAPIKey(ctx, openaiApiKeyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOpenAIAPIKey", reflect.TypeOf((*MockAgentPlatformService)(nil).DeleteOpenAIAPIKey), ctx, openaiApiKeyId)
}

// DeleteScenarioSet mocks base method.
func (m *MockAgentPlatformService) DeleteScenarioSet(ctx context.Context, scenarioSetUUID string) (*godo.ScenarioSetDeleteResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScenarioSet", ctx, scenarioSetUUID)
	ret0, _ := ret[0].(*godo.ScenarioSetDeleteResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteScenarioSet indicates an expected call of DeleteScenarioSet.
func (mr *MockAgentPlatformServiceMockRecorder) DeleteScenarioSet(ctx, scenarioSetUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScenarioSet", reflect.TypeOf((*MockAgentPlatformService)(nil).DeleteScenarioSet), ctx, scenarioSetUUID)
}

// DeleteSimulationRun mocks base method.
func (m *MockAgentPlatformService) DeleteSimulationRun(ctx context.Context, runUUID string) (*godo.SimulationRunDeleteResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSimulationRun", ctx, runUUID)
	ret0, _ := ret[0].(*godo.SimulationRunDeleteResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteSimulationRun indicates an expected call of DeleteSimulationRun.
func (mr *MockAgentPlatformServiceMockRecorder) DeleteSimulationRun(ctx, runUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSimulationRun", reflect.TypeOf((*MockAgentPlatformService)(nil).DeleteSimulationRun), ctx, runUUID)
}

// DetachKnowledgeBaseToAgent mocks base method.
func (m *MockAgentPlatformService) DetachKnowledgeBaseToAgent(ctx context.Context, agentID, knowledgeBaseID string) (*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachKnowledgeBaseToAgent", ctx, agentID, knowledgeBaseID)
	ret0, _ := ret[0].(*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DetachKnowledgeBaseToAgent indicates an expected call of DetachKnowledgeBaseToAgent.
func (mr *MockAgentPlatformServiceMockRecorder) DetachKnowledgeBaseToAgent(ctx, agentID, knowledgeBaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachKnowledgeBaseToAgent", reflect.TypeOf((*MockAgentPlatformService)(nil).DetachKnowledgeBaseToAgent), ctx, agentID, knowledgeBaseID)
}

// GenerateScenarioSet mocks base method.
func (m *MockAgentPlatformService) GenerateScenarioSet(ctx context.Context, generateRequest *godo.GenerateScenarioSetRequest) (*godo.ScenarioSet, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateScenarioSet", ctx, generateRequest)
	ret0, _ := ret[0].(*godo.ScenarioSet)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateScenarioSet indicates an expected call of GenerateScenarioSet.
func (mr *MockAgentPlatformServiceMockRecorder) GenerateScenarioSet(ctx, generateRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateScenarioSet", reflect.TypeOf((*MockAgentPlatformService)(nil).GenerateScenarioSet), ctx, generateRequest)
}

// GetAgent mocks base method.
func (m *MockAgentPlatformService) GetAgent(arg0 context.Context, arg1 string) (*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgent", arg0, arg1)
	ret0, _ := ret[0].(*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAgent indicates an expected call of GetAgent.
func (mr *MockAgentPlatformServiceMockRecorder) GetAgent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgent", reflect.TypeOf((*MockAgentPlatformService)(nil).GetAgent), arg0, arg1)
}

// GetAnthropicAPIKey mocks base method.
func (m *MockAgentPlatformService) GetAnthropicAPIKey(ctx context.Context, id string) (*godo.AnthropicApiKeyInfo, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnthropicAPIKey", ctx, id)
	ret0, _ := ret[0].(*godo.AnthropicApiKeyInfo)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAnthropicAPIKey indicates an expected call of GetAnthropicAPIKey.
func (mr *MockAgentPlatformServiceMockRecorder) GetAnthropicAPIKey(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnthropicAPIKey", reflect.TypeOf((*MockAgentPlatformService)(nil).GetAnthropicAPIKey), ctx, id)
}

// GetCustomModel mocks base method.
func (m *MockAgentPlatformService) GetCustomModel(ctx context.Context, uuid string) (*godo.CustomModel, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomModel", ctx, uuid)
	ret0, _ := ret[0].(*godo.CustomModel)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCustomModel indicates an expected call of GetCustomModel.
func (mr *MockAgentPlatformServiceMockRecorder) GetCustomModel(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomModel", reflect.TypeOf((*MockAgentPlatformService)(nil).GetCustomModel), ctx, uuid)
}

// GetIndexingJob mocks base method.
func (m *MockAgentPlatformService) GetIndexingJob(ctx context.Context, indexingJobUUID string) (*godo.IndexingJobResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndexingJob", ctx, indexingJobUUID)
	ret0, _ := ret[0].(*godo.IndexingJobResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetIndexingJob indicates an expected call of GetIndexingJob.
func (mr *MockAgentPlatformServiceMockRecorder) GetIndexingJob(ctx, indexingJobUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndexingJob", reflect.TypeOf((*MockAgentPlatformService)(nil).GetIndexingJob), ctx, indexingJobUUID)
}

// GetInferenceRouter mocks base method.
func (m *MockAgentPlatformService) GetInferenceRouter(arg0 context.Context, arg1 string) (*godo.InferenceRouter, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInferenceRouter", arg0, arg1)
	ret0, _ := ret[0].(*godo.InferenceRouter)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetInferenceRouter indicates an expected call of GetInferenceRouter.
func (mr *MockAgentPlatformServiceMockRecorder) GetInferenceRouter(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInferenceRouter", reflect.TypeOf((*MockAgentPlatformService)(nil).GetInferenceRouter), arg0, arg1)
}

// GetKnowledgeBase mocks base method.
func (m *MockAgentPlatformService) GetKnowledgeBase(ctx context.Context, knowledgeBaseID string) (*godo.KnowledgeBase, string, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKnowledgeBase", ctx, knowledgeBaseID)
	ret0, _ := ret[0].(*godo.KnowledgeBase)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(*godo.Response)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetKnowledgeBase indicates an expected call of GetKnowledgeBase.
func (mr *MockAgentPlatformServiceMockRecorder) GetKnowledgeBase(ctx, knowledgeBaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKnowledgeBase", reflect.TypeOf((*MockAgentPlatformService)(nil).GetKnowledgeBase), ctx, knowledgeBaseID)
}

// GetModelByUUID mocks base method.
func (m *MockAgentPlatformService) GetModelByUUID(arg0 context.Context, arg1 string) (*godo.Model, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelByUUID", arg0, arg1)
	ret0, _ := ret[0].(*godo.Model)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetModelByUUID indicates an expected call of GetModelByUUID.
func (mr *MockAgentPlatformServiceMockRecorder) GetModelByUUID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelByUUID", reflect.TypeOf((*MockAgentPlatformService)(nil).GetModelByUUID), arg0, arg1)
}

// GetModelEvaluationPreset mocks base method.
func (m *MockAgentPlatformService) GetModelEvaluationPreset(ctx context.Context, evalPresetUUID string) (*godo.ModelEvaluationPresetGetResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelEvaluationPreset", ctx, evalPresetUUID)
	ret0, _ := ret[0].(*godo.ModelEvaluationPresetGetResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetModelEvaluationPreset indicates an expected call of GetModelEvaluationPreset.
func (mr *MockAgentPlatformServiceMockRecorder) GetModelEvaluationPreset(ctx, evalPresetUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelEvaluationPreset", reflect.TypeOf((*MockAgentPlatformService)(nil).GetModelEvaluationPreset), ctx, evalPresetUUID)
}

// GetModelEvaluationRun mocks base method.
func (m *MockAgentPlatformService) GetModelEvaluationRun(ctx context.Context, evalRunUUID string, opt *godo.ModelEvaluationRunGetOptions) (*godo.ModelEvaluationRunGetResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelEvaluationRun", ctx, evalRunUUID, opt)
	ret0, _ := ret[0].(*godo.ModelEvaluationRunGetResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetModelEvaluationRun indicates an expected call of GetModelEvaluationRun.
func (mr *MockAgentPlatformServiceMockRecorder) GetModelEvaluationRun(ctx, evalRunUUID, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelEvaluationRun", reflect.TypeOf((*MockAgentPlatformService)(nil).GetModelEvaluationRun), ctx, evalRunUUID, opt)
}

// GetModelEvaluationRunResultsDownloadURL mocks base method.
func (m *MockAgentPlatformService) GetModelEvaluationRunResultsDownloadURL(ctx context.Context, evalRunUUID string) (*godo.ModelEvaluationRunResultsDownloadURLResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelEvaluationRunResultsDownloadURL", ctx, evalRunUUID)
	ret0, _ := ret[0].(*godo.ModelEvaluationRunResultsDownloadURLResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetModelEvaluationRunResultsDownloadURL indicates an expected call of GetModelEvaluationRunResultsDownloadURL.
func (mr *MockAgentPlatformServiceMockRecorder) GetModelEvaluationRunResultsDownloadURL(ctx, evalRunUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelEvaluationRunResultsDownloadURL", reflect.TypeOf((*MockAgentPlatformService)(nil).GetModelEvaluationRunResultsDownloadURL), ctx, evalRunUUID)
}

// GetOpenAIAPIKey mocks base method.
func (m *MockAgentPlatformService) GetOpenAIAPIKey(ctx context.Context, openaiApiKeyId string) (*godo.OpenAiApiKey, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenAIAPIKey", ctx, openaiApiKeyId)
	ret0, _ := ret[0].(*godo.OpenAiApiKey)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetOpenAIAPIKey indicates an expected call of GetOpenAIAPIKey.
func (mr *MockAgentPlatformServiceMockRecorder) GetOpenAIAPIKey(ctx, openaiApiKeyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenAIAPIKey", reflect.TypeOf((*MockAgentPlatformService)(nil).GetOpenAIAPIKey), ctx, openaiApiKeyId)
}

// GetScenarioSet mocks base method.
func (m *MockAgentPlatformService) GetScenarioSet(ctx context.Context, scenarioSetUUID string) (*godo.ScenarioSet, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScenarioSet", ctx, scenarioSetUUID)
	ret0, _ := ret[0].(*godo.ScenarioSet)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetScenarioSet indicates an expected call of GetScenarioSet.
func (mr *MockAgentPlatformServiceMockRecorder) GetScenarioSet(ctx, scenarioSetUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScenarioSet", reflect.TypeOf((*MockAgentPlatformService)(nil).GetScenarioSet), ctx, scenarioSetUUID)
}

// GetScenarioSetDownloadURL mocks base method.
func (m *MockAgentPlatformService) GetScenarioSetDownloadURL(ctx context.Context, scenarioSetUUID string) (*godo.ScenarioSetDownloadURLResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScenarioSetDownloadURL", ctx, scenarioSetUUID)
	ret0, _ := ret[0].(*godo.ScenarioSetDownloadURLResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetScenarioSetDownloadURL indicates an expected call of GetScenarioSetDownloadURL.
func (mr *MockAgentPlatformServiceMockRecorder) GetScenarioSetDownloadURL(ctx, scenarioSetUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScenarioSetDownloadURL", reflect.TypeOf((*MockAgentPlatformService)(nil).GetScenarioSetDownloadURL), ctx, scenarioSetUUID)
}

// GetSimulationJourney mocks base method.
func (m *MockAgentPlatformService) GetSimulationJourney(ctx context.Context, runUUID, journeyUUID string) (*godo.SimulationJourney, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimulationJourney", ctx, runUUID, journeyUUID)
	ret0, _ := ret[0].(*godo.SimulationJourney)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSimulationJourney indicates an expected call of GetSimulationJourney.
func (mr *MockAgentPlatformServiceMockRecorder) GetSimulationJourney(ctx, runUUID, journeyUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimulationJourney", reflect.TypeOf((*MockAgentPlatformService)(nil).GetSimulationJourney), ctx, runUUID, journeyUUID)
}

// GetSimulationJourneyTrajectory mocks base method.
func (m *MockAgentPlatformService) GetSimulationJourneyTrajectory(ctx context.Context, runUUID, journeyUUID string) (*godo.SimulationTrajectory, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimulationJourneyTrajectory", ctx, runUUID, journeyUUID)
	ret0, _ := ret[0].(*godo.SimulationTrajectory)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSimulationJourneyTrajectory indicates an expected call of GetSimulationJourneyTrajectory.
func (mr *MockAgentPlatformServiceMockRecorder) GetSimulationJourneyTrajectory(ctx, runUUID, journeyUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimulationJourneyTrajectory", reflect.TypeOf((*MockAgentPlatformService)(nil).GetSimulationJourneyTrajectory), ctx, runUUID, journeyUUID)
}

// GetSimulationJourneyTrajectoryURL mocks base method.
func (m *MockAgentPlatformService) GetSimulationJourneyTrajectoryURL(ctx context.Context, runUUID, journeyUUID string) (*godo.SimulationJourneyTrajectoryURLResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimulationJourneyTrajectoryURL", ctx, runUUID, journeyUUID)
	ret0, _ := ret[0].(*godo.SimulationJourneyTrajectoryURLResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSimulationJourneyTrajectoryURL indicates an expected call of GetSimulationJourneyTrajectoryURL.
func (mr *MockAgentPlatformServiceMockRecorder) GetSimulationJourneyTrajectoryURL(ctx, runUUID, journeyUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimulationJourneyTrajectoryURL", reflect.TypeOf((*MockAgentPlatformService)(nil).GetSimulationJourneyTrajectoryURL), ctx, runUUID, journeyUUID)
}

// GetSimulationRun mocks base method.
func (m *MockAgentPlatformService) GetSimulationRun(ctx context.Context, runUUID string) (*godo.SimulationRunGetResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimulationRun", ctx, runUUID)
	ret0, _ := ret[0].(*godo.SimulationRunGetResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSimulationRun indicates an expected call of GetSimulationRun.
func (mr *MockAgentPlatformServiceMockRecorder) GetSimulationRun(ctx, runUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimulationRun", reflect.TypeOf((*MockAgentPlatformService)(nil).GetSimulationRun), ctx, runUUID)
}

// ImportCustomModel mocks base method.
func (m *MockAgentPlatformService) ImportCustomModel(ctx context.Context, importRequest *godo.CustomModelImportRequest) (*godo.CustomModelImportResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportCustomModel", ctx, importRequest)
	ret0, _ := ret[0].(*godo.CustomModelImportResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ImportCustomModel indicates an expected call of ImportCustomModel.
func (mr *MockAgentPlatformServiceMockRecorder) ImportCustomModel(ctx, importRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportCustomModel", reflect.TypeOf((*MockAgentPlatformService)(nil).ImportCustomModel), ctx, importRequest)
}

// ListAgentAPIKeys mocks base method.
func (m *MockAgentPlatformService) ListAgentAPIKeys(arg0 context.Context, arg1 string, arg2 *godo.ListOptions) ([]*godo.ApiKeyInfo, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgentAPIKeys", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*godo.ApiKeyInfo)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAgentAPIKeys indicates an expected call of ListAgentAPIKeys.
func (mr *MockAgentPlatformServiceMockRecorder) ListAgentAPIKeys(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgentAPIKeys", reflect.TypeOf((*MockAgentPlatformService)(nil).ListAgentAPIKeys), arg0, arg1, arg2)
}

// ListAgentVersions mocks base method.
func (m *MockAgentPlatformService) ListAgentVersions(arg0 context.Context, arg1 string, arg2 *godo.ListOptions) ([]*godo.AgentVersion, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgentVersions", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*godo.AgentVersion)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAgentVersions indicates an expected call of ListAgentVersions.
func (mr *MockAgentPlatformServiceMockRecorder) ListAgentVersions(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgentVersions", reflect.TypeOf((*MockAgentPlatformService)(nil).ListAgentVersions), arg0, arg1, arg2)
}

// ListAgents mocks base method.
func (m *MockAgentPlatformService) ListAgents(arg0 context.Context, arg1 *godo.ListOptions) ([]*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgents", arg0, arg1)
	ret0, _ := ret[0].([]*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAgents indicates an expected call of ListAgents.
func (mr *MockAgentPlatformServiceMockRecorder) ListAgents(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgents", reflect.TypeOf((*MockAgentPlatformService)(nil).ListAgents), arg0, arg1)
}

// ListAgentsByAnthropicAPIKey mocks base method.
func (m *MockAgentPlatformService) ListAgentsByAnthropicAPIKey(ctx context.Context, id string, opt *godo.ListOptions) ([]*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgentsByAnthropicAPIKey", ctx, id, opt)
	ret0, _ := ret[0].([]*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAgentsByAnthropicAPIKey indicates an expected call of ListAgentsByAnthropicAPIKey.
func (mr *MockAgentPlatformServiceMockRecorder) ListAgentsByAnthropicAPIKey(ctx, id, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgentsByAnthropicAPIKey", reflect.TypeOf((*MockAgentPlatformService)(nil).ListAgentsByAnthropicAPIKey), ctx, id, opt)
}

// ListAgentsByOpenAIAPIKey mocks base method.
func (m *MockAgentPlatformService) ListAgentsByOpenAIAPIKey(ctx context.Context, openaiApiKeyId string, opt *godo.ListOptions) ([]*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgentsByOpenAIAPIKey", ctx, openaiApiKeyId, opt)
	ret0, _ := ret[0].([]*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAgentsByOpenAIAPIKey indicates an expected call of ListAgentsByOpenAIAPIKey.
func (mr *MockAgentPlatformServiceMockRecorder) ListAgentsByOpenAIAPIKey(ctx, openaiApiKeyId, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgentsByOpenAIAPIKey", reflect.TypeOf((*MockAgentPlatformService)(nil).ListAgentsByOpenAIAPIKey), ctx, openaiApiKeyId, opt)
}

// ListAnthropicAPIKeys mocks base method.
func (m *MockAgentPlatformService) ListAnthropicAPIKeys(arg0 context.Context, arg1 *godo.ListOptions) ([]*godo.AnthropicApiKeyInfo, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAnthropicAPIKeys", arg0, arg1)
	ret0, _ := ret[0].([]*godo.AnthropicApiKeyInfo)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAnthropicAPIKeys indicates an expected call of ListAnthropicAPIKeys.
func (mr *MockAgentPlatformServiceMockRecorder) ListAnthropicAPIKeys(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAnthropicAPIKeys", reflect.TypeOf((*MockAgentPlatformService)(nil).ListAnthropicAPIKeys), arg0, arg1)
}

// ListAvailableModels mocks base method.
func (m *MockAgentPlatformService) ListAvailableModels(arg0 context.Context, arg1 *godo.ListOptions) ([]*godo.Model, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAvailableModels", arg0, arg1)
	ret0, _ := ret[0].([]*godo.Model)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAvailableModels indicates an expected call of ListAvailableModels.
func (mr *MockAgentPlatformServiceMockRecorder) ListAvailableModels(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAvailableModels", reflect.TypeOf((*MockAgentPlatformService)(nil).ListAvailableModels), arg0, arg1)
}

// ListCustomModels mocks base method.
func (m *MockAgentPlatformService) ListCustomModels(ctx context.Context, opt *godo.CustomModelListOptions) (*godo.CustomModelListResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCustomModels", ctx, opt)
	ret0, _ := ret[0].(*godo.CustomModelListResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCustomModels indicates an expected call of ListCustomModels.
func (mr *MockAgentPlatformServiceMockRecorder) ListCustomModels(ctx, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCustomModels", reflect.TypeOf((*MockAgentPlatformService)(nil).ListCustomModels), ctx, opt)
}

// ListDatacenterRegions mocks base method.
func (m *MockAgentPlatformService) ListDatacenterRegions(arg0 context.Context, arg1, arg2 *bool) ([]*godo.DatacenterRegions, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDatacenterRegions", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*godo.DatacenterRegions)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListDatacenterRegions indicates an expected call of ListDatacenterRegions.
func (mr *MockAgentPlatformServiceMockRecorder) ListDatacenterRegions(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDatacenterRegions", reflect.TypeOf((*MockAgentPlatformService)(nil).ListDatacenterRegions), arg0, arg1, arg2)
}

// ListEvaluationDatasets mocks base method.
func (m *MockAgentPlatformService) ListEvaluationDatasets(ctx context.Context, opt *godo.EvaluationDatasetListOptions) (*godo.EvaluationDatasetListResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvaluationDatasets", ctx, opt)
	ret0, _ := ret[0].(*godo.EvaluationDatasetListResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListEvaluationDatasets indicates an expected call of ListEvaluationDatasets.
func (mr *MockAgentPlatformServiceMockRecorder) ListEvaluationDatasets(ctx, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvaluationDatasets", reflect.TypeOf((*MockAgentPlatformService)(nil).ListEvaluationDatasets), ctx, opt)
}

// ListIndexingJobDataSources mocks base method.
func (m *MockAgentPlatformService) ListIndexingJobDataSources(ctx context.Context, indexingJobUUID string) (*godo.IndexingJobDataSourcesResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIndexingJobDataSources", ctx, indexingJobUUID)
	ret0, _ := ret[0].(*godo.IndexingJobDataSourcesResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListIndexingJobDataSources indicates an expected call of ListIndexingJobDataSources.
func (mr *MockAgentPlatformServiceMockRecorder) ListIndexingJobDataSources(ctx, indexingJobUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIndexingJobDataSources", reflect.TypeOf((*MockAgentPlatformService)(nil).ListIndexingJobDataSources), ctx, indexingJobUUID)
}

// ListIndexingJobs mocks base method.
func (m *MockAgentPlatformService) ListIndexingJobs(ctx context.Context, opt *godo.ListOptions) (*godo.IndexingJobsResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIndexingJobs", ctx, opt)
	ret0, _ := ret[0].(*godo.IndexingJobsResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListIndexingJobs indicates an expected call of ListIndexingJobs.
func (mr *MockAgentPlatformServiceMockRecorder) ListIndexingJobs(ctx, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIndexingJobs", reflect.TypeOf((*MockAgentPlatformService)(nil).ListIndexingJobs), ctx, opt)
}

// ListInferenceRouterTaskPresets mocks base method.
func (m *MockAgentPlatformService) ListInferenceRouterTaskPresets(arg0 context.Context, arg1 *godo.ListOptions) ([]*godo.InferenceRouterTaskPreset, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInferenceRouterTaskPresets", arg0, arg1)
	ret0, _ := ret[0].([]*godo.InferenceRouterTaskPreset)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListInferenceRouterTaskPresets indicates an expected call of ListInferenceRouterTaskPresets.
func (mr *MockAgentPlatformServiceMockRecorder) ListInferenceRouterTaskPresets(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInferenceRouterTaskPresets", reflect.TypeOf((*MockAgentPlatformService)(nil).ListInferenceRouterTaskPresets), arg0, arg1)
}

// ListInferenceRouters mocks base method.
func (m *MockAgentPlatformService) ListInferenceRouters(arg0 context.Context, arg1 *godo.ListOptions) ([]*godo.InferenceRouterSummary, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInferenceRouters", arg0, arg1)
	ret0, _ := ret[0].([]*godo.InferenceRouterSummary)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListInferenceRouters indicates an expected call of ListInferenceRouters.
func (mr *MockAgentPlatformServiceMockRecorder) ListInferenceRouters(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInferenceRouters", reflect.TypeOf((*MockAgentPlatformService)(nil).ListInferenceRouters), arg0, arg1)
}

// ListKnowledgeBaseDataSources mocks base method.
func (m *MockAgentPlatformService) ListKnowledgeBaseDataSources(ctx context.Context, knowledgeBaseID string, opt *godo.ListOptions) ([]godo.KnowledgeBaseDataSource, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKnowledgeBaseDataSources", ctx, knowledgeBaseID, opt)
	ret0, _ := ret[0].([]godo.KnowledgeBaseDataSource)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListKnowledgeBaseDataSources indicates an expected call of ListKnowledgeBaseDataSources.
func (mr *MockAgentPlatformServiceMockRecorder) ListKnowledgeBaseDataSources(ctx, knowledgeBaseID, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKnowledgeBaseDataSources", reflect.TypeOf((*MockAgentPlatformService)(nil).ListKnowledgeBaseDataSources), ctx, knowledgeBaseID, opt)
}

// ListKnowledgeBases mocks base method.
func (m *MockAgentPlatformService) ListKnowledgeBases(ctx context.Context, opt *godo.ListOptions) ([]godo.KnowledgeBase, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKnowledgeBases", ctx, opt)
	ret0, _ := ret[0].([]godo.KnowledgeBase)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListKnowledgeBases indicates an expected call of ListKnowledgeBases.
func (mr *MockAgentPlatformServiceMockRecorder) ListKnowledgeBases(ctx, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKnowledgeBases", reflect.TypeOf((*MockAgentPlatformService)(nil).ListKnowledgeBases), ctx, opt)
}

// ListModelEvaluationMetrics mocks base method.
func (m *MockAgentPlatformService) ListModelEvaluationMetrics(ctx context.Context) (*godo.ModelEvaluationMetricListResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModelEvaluationMetrics", ctx)
	ret0, _ := ret[0].(*godo.ModelEvaluationMetricListResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListModelEvaluationMetrics indicates an expected call of ListModelEvaluationMetrics.
func (mr *MockAgentPlatformServiceMockRecorder) ListModelEvaluationMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModelEvaluationMetrics", reflect.TypeOf((*MockAgentPlatformService)(nil).ListModelEvaluationMetrics), ctx)
}

// ListModelEvaluationPresets mocks base method.
func (m *MockAgentPlatformService) ListModelEvaluationPresets(ctx context.Context) (*godo.ModelEvaluationPresetListResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModelEvaluationPresets", ctx)
	ret0, _ := ret[0].(*godo.ModelEvaluationPresetListResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListModelEvaluationPresets indicates an expected call of ListModelEvaluationPresets.
func (mr *MockAgentPlatformServiceMockRecorder) ListModelEvaluationPresets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModelEvaluationPresets", reflect.TypeOf((*MockAgentPlatformService)(nil).ListModelEvaluationPresets), ctx)
}

// ListModelEvaluationRuns mocks base method.
func (m *MockAgentPlatformService) ListModelEvaluationRuns(ctx context.Context, opt *godo.ModelEvaluationRunListOptions) (*godo.ModelEvaluationRunListResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModelEvaluationRuns", ctx, opt)
	ret0, _ := ret[0].(*godo.ModelEvaluationRunListResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListModelEvaluationRuns indicates an expected call of ListModelEvaluationRuns.
func (mr *MockAgentPlatformServiceMockRecorder) ListModelEvaluationRuns(ctx, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModelEvaluationRuns", reflect.TypeOf((*MockAgentPlatformService)(nil).ListModelEvaluationRuns), ctx, opt)
}

// ListOpenAIAPIKeys mocks base method.
func (m *MockAgentPlatformService) ListOpenAIAPIKeys(arg0 context.Context, arg1 *godo.ListOptions) ([]*godo.OpenAiApiKey, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOpenAIAPIKeys", arg0, arg1)
	ret0, _ := ret[0].([]*godo.OpenAiApiKey)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListOpenAIAPIKeys indicates an expected call of ListOpenAIAPIKeys.
func (mr *MockAgentPlatformServiceMockRecorder) ListOpenAIAPIKeys(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOpenAIAPIKeys", reflect.TypeOf((*MockAgentPlatformService)(nil).ListOpenAIAPIKeys), arg0, arg1)
}

// ListScenarioLibrary mocks base method.
func (m *MockAgentPlatformService) ListScenarioLibrary(ctx context.Context, opt *godo.ScenarioLibraryListOptions) (*godo.ScenarioLibraryListResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScenarioLibrary", ctx, opt)
	ret0, _ := ret[0].(*godo.ScenarioLibraryListResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListScenarioLibrary indicates an expected call of ListScenarioLibrary.
func (mr *MockAgentPlatformServiceMockRecorder) ListScenarioLibrary(ctx, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScenarioLibrary", reflect.TypeOf((*MockAgentPlatformService)(nil).ListScenarioLibrary), ctx, opt)
}

// ListScenarioLibraryScenarios mocks base method.
func (m *MockAgentPlatformService) ListScenarioLibraryScenarios(ctx context.Context, libraryScenarioUUID string, opt *godo.ScenarioListOptions) (*godo.ScenarioListResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScenarioLibraryScenarios", ctx, libraryScenarioUUID, opt)
	ret0, _ := ret[0].(*godo.ScenarioListResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListScenarioLibraryScenarios indicates an expected call of ListScenarioLibraryScenarios.
func (mr *MockAgentPlatformServiceMockRecorder) ListScenarioLibraryScenarios(ctx, libraryScenarioUUID, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScenarioLibraryScenarios", reflect.TypeOf((*MockAgentPlatformService)(nil).ListScenarioLibraryScenarios), ctx, libraryScenarioUUID, opt)
}

// ListScenarioSets mocks base method.
func (m *MockAgentPlatformService) ListScenarioSets(ctx context.Context, opt *godo.ScenarioSetListOptions) (*godo.ScenarioSetListResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScenarioSets", ctx, opt)
	ret0, _ := ret[0].(*godo.ScenarioSetListResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListScenarioSets indicates an expected call of ListScenarioSets.
func (mr *MockAgentPlatformServiceMockRecorder) ListScenarioSets(ctx, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScenarioSets", reflect.TypeOf((*MockAgentPlatformService)(nil).ListScenarioSets), ctx, opt)
}

// ListScenarios mocks base method.
func (m *MockAgentPlatformService) ListScenarios(ctx context.Context, scenarioSetUUID string, opt *godo.ScenarioListOptions) (*godo.ScenarioListResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScenarios", ctx, scenarioSetUUID, opt)
	ret0, _ := ret[0].(*godo.ScenarioListResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListScenarios indicates an expected call of ListScenarios.
func (mr *MockAgentPlatformServiceMockRecorder) ListScenarios(ctx, scenarioSetUUID, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScenarios", reflect.TypeOf((*MockAgentPlatformService)(nil).ListScenarios), ctx, scenarioSetUUID, opt)
}

// ListSimulationJourneys mocks base method.
func (m *MockAgentPlatformService) ListSimulationJourneys(ctx context.Context, runUUID string, opt *godo.SimulationJourneyListOptions) (*godo.SimulationJourneyListResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSimulationJourneys", ctx, runUUID, opt)
	ret0, _ := ret[0].(*godo.SimulationJourneyListResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSimulationJourneys indicates an expected call of ListSimulationJourneys.
func (mr *MockAgentPlatformServiceMockRecorder) ListSimulationJourneys(ctx, runUUID, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSimulationJourneys", reflect.TypeOf((*MockAgentPlatformService)(nil).ListSimulationJourneys), ctx, runUUID, opt)
}

// ListSimulationRuns mocks base method.
func (m *MockAgentPlatformService) ListSimulationRuns(ctx context.Context, opt *godo.SimulationRunListOptions) (*godo.SimulationRunListResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSimulationRuns", ctx, opt)
	ret0, _ := ret[0].(*godo.SimulationRunListResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSimulationRuns indicates an expected call of ListSimulationRuns.
func (mr *MockAgentPlatformServiceMockRecorder) ListSimulationRuns(ctx, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSimulationRuns", reflect.TypeOf((*MockAgentPlatformService)(nil).ListSimulationRuns), ctx, opt)
}

// RegenerateAgentAPIKey mocks base method.
func (m *MockAgentPlatformService) RegenerateAgentAPIKey(arg0 context.Context, arg1, arg2 string) (*godo.ApiKeyInfo, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegenerateAgentAPIKey", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.ApiKeyInfo)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RegenerateAgentAPIKey indicates an expected call of RegenerateAgentAPIKey.
func (mr *MockAgentPlatformServiceMockRecorder) RegenerateAgentAPIKey(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegenerateAgentAPIKey", reflect.TypeOf((*MockAgentPlatformService)(nil).RegenerateAgentAPIKey), arg0, arg1, arg2)
}

// RollbackAgentVersion mocks base method.
func (m *MockAgentPlatformService) RollbackAgentVersion(arg0 context.Context, arg1, arg2 string) (string, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackAgentVersion", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RollbackAgentVersion indicates an expected call of RollbackAgentVersion.
func (mr *MockAgentPlatformServiceMockRecorder) RollbackAgentVersion(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackAgentVersion", reflect.TypeOf((*MockAgentPlatformService)(nil).RollbackAgentVersion), arg0, arg1, arg2)
}

// SearchModels mocks base method.
func (m *MockAgentPlatformService) SearchModels(arg0 context.Context, arg1 string) ([]string, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchModels", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchModels indicates an expected call of SearchModels.
func (mr *MockAgentPlatformServiceMockRecorder) SearchModels(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchModels", reflect.TypeOf((*MockAgentPlatformService)(nil).SearchModels), arg0, arg1)
}

// UpdateAgent mocks base method.
func (m *MockAgentPlatformService) UpdateAgent(arg0 context.Context, arg1 string, arg2 *godo.AgentUpdateRequest) (*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAgent", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateAgent indicates an expected call of UpdateAgent.
func (mr *MockAgentPlatformServiceMockRecorder) UpdateAgent(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAgent", reflect.TypeOf((*MockAgentPlatformService)(nil).UpdateAgent), arg0, arg1, arg2)
}

// UpdateAgentAPIKey mocks base method.
func (m *MockAgentPlatformService) UpdateAgentAPIKey(arg0 context.Context, arg1, arg2 string, arg3 *godo.AgentAPIKeyUpdateRequest) (*godo.ApiKeyInfo, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAgentAPIKey", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*godo.ApiKeyInfo)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateAgentAPIKey indicates an expected call of UpdateAgentAPIKey.
func (mr *MockAgentPlatformServiceMockRecorder) UpdateAgentAPIKey(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAgentAPIKey", reflect.TypeOf((*MockAgentPlatformService)(nil).UpdateAgentAPIKey), arg0, arg1, arg2, arg3)
}

// UpdateAgentRoute mocks base method.
func (m *MockAgentPlatformService) UpdateAgentRoute(arg0 context.Context, arg1, arg2 string, arg3 *godo.AgentRouteUpdateRequest) (*godo.AgentRouteResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAgentRoute", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*godo.AgentRouteResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateAgentRoute indicates an expected call of UpdateAgentRoute.
func (mr *MockAgentPlatformServiceMockRecorder) UpdateAgentRoute(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAgentRoute", reflect.TypeOf((*MockAgentPlatformService)(nil).UpdateAgentRoute), arg0, arg1, arg2, arg3)
}

// UpdateAgentVisibility mocks base method.
func (m *MockAgentPlatformService) UpdateAgentVisibility(arg0 context.Context, arg1 string, arg2 *godo.AgentVisibilityUpdateRequest) (*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAgentVisibility", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateAgentVisibility indicates an expected call of UpdateAgentVisibility.
func (mr *MockAgentPlatformServiceMockRecorder) UpdateAgentVisibility(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAgentVisibility", reflect.TypeOf((*MockAgentPlatformService)(nil).UpdateAgentVisibility), arg0, arg1, arg2)
}

// UpdateAnthropicAPIKey mocks base method.
func (m *MockAgentPlatformService) UpdateAnthropicAPIKey(ctx context.Context, id string, anthropicAPIKeyUpdateRequest *godo.AnthropicAPIKeyUpdateRequest) (*godo.AnthropicApiKeyInfo, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAnthropicAPIKey", ctx, id, anthropicAPIKeyUpdateRequest)
	ret0, _ := ret[0].(*godo.AnthropicApiKeyInfo)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateAnthropicAPIKey indicates an expected call of UpdateAnthropicAPIKey.
func (mr *MockAgentPlatformServiceMockRecorder) UpdateAnthropicAPIKey(ctx, id, anthropicAPIKeyUpdateRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAnthropicAPIKey", reflect.TypeOf((*MockAgentPlatformService)(nil).UpdateAnthropicAPIKey), ctx, id, anthropicAPIKeyUpdateRequest)
}

// UpdateCustomEvaluationMetric mocks base method.
func (m *MockAgentPlatformService) UpdateCustomEvaluationMetric(ctx context.Context, metricUUID string, updateRequest *godo.UpdateCustomEvaluationMetricRequest) (*godo.EvaluationMetric, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomEvaluationMetric", ctx, metricUUID, updateRequest)
	ret0, _ := ret[0].(*godo.EvaluationMetric)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateCustomEvaluationMetric indicates an expected call of UpdateCustomEvaluationMetric.
func (mr *MockAgentPlatformServiceMockRecorder) UpdateCustomEvaluationMetric(ctx, metricUUID, updateRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomEvaluationMetric", reflect.TypeOf((*MockAgentPlatformService)(nil).UpdateCustomEvaluationMetric), ctx, metricUUID, updateRequest)
}

// UpdateCustomModelMetadata mocks base method.
func (m *MockAgentPlatformService) UpdateCustomModelMetadata(ctx context.Context, uuid string, updateRequest *godo.CustomModelMetadataUpdateRequest) (*godo.CustomModel, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomModelMetadata", ctx, uuid, updateRequest)
	ret0, _ := ret[0].(*godo.CustomModel)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateCustomModelMetadata indicates an expected call of UpdateCustomModelMetadata.
func (mr *MockAgentPlatformServiceMockRecorder) UpdateCustomModelMetadata(ctx, uuid, updateRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomModelMetadata", reflect.TypeOf((*MockAgentPlatformService)(nil).UpdateCustomModelMetadata), ctx, uuid, updateRequest)
}

// UpdateFunctionRoute mocks base method.
func (m *MockAgentPlatformService) UpdateFunctionRoute(arg0 context.Context, arg1, arg2 string, arg3 *godo.FunctionRouteUpdateRequest) (*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFunctionRoute", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateFunctionRoute indicates an expected call of UpdateFunctionRoute.
func (mr *MockAgentPlatformServiceMockRecorder) UpdateFunctionRoute(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFunctionRoute", reflect.TypeOf((*MockAgentPlatformService)(nil).UpdateFunctionRoute), arg0, arg1, arg2, arg3)
}

// UpdateInferenceRouter mocks base method.
func (m *MockAgentPlatformService) UpdateInferenceRouter(arg0 context.Context, arg1 string, arg2 *godo.InferenceRouterUpdateRequest) (*godo.InferenceRouter, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInferenceRouter", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.InferenceRouter)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateInferenceRouter indicates an expected call of UpdateInferenceRouter.
func (mr *MockAgentPlatformServiceMockRecorder) UpdateInferenceRouter(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInferenceRouter", reflect.TypeOf((*MockAgentPlatformService)(nil).UpdateInferenceRouter), arg0, arg1, arg2)
}

// UpdateKnowledgeBase mocks base method.
func (m *MockAgentPlatformService) UpdateKnowledgeBase(ctx context.Context, knowledgeBaseID string, update *godo.UpdateKnowledgeBaseRequest) (*godo.KnowledgeBase, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKnowledgeBase", ctx, knowledgeBaseID, update)
	ret0, _ := ret[0].(*godo.KnowledgeBase)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateKnowledgeBase indicates an expected call of UpdateKnowledgeBase.
func (mr *MockAgentPlatformServiceMockRecorder) UpdateKnowledgeBase(ctx, knowledgeBaseID, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKnowledgeBase", reflect.TypeOf((*MockAgentPlatformService)(nil).UpdateKnowledgeBase), ctx, knowledgeBaseID, update)
}

// UpdateModelEvaluationRun mocks base method.
func (m *MockAgentPlatformService) UpdateModelEvaluationRun(ctx context.Context, evalRunUUID string, updateRequest *godo.UpdateModelEvaluationRunRequest) (*godo.ModelEvaluationRunUpdateResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateModelEvaluationRun", ctx, evalRunUUID, updateRequest)
	ret0, _ := ret[0].(*godo.ModelEvaluationRunUpdateResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateModelEvaluationRun indicates an expected call of UpdateModelEvaluationRun.
func (mr *MockAgentPlatformServiceMockRecorder) UpdateModelEvaluationRun(ctx, evalRunUUID, updateRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateModelEvaluationRun", reflect.TypeOf((*MockAgentPlatformService)(nil).UpdateModelEvaluationRun), ctx, evalRunUUID, updateRequest)
}

// UpdateOpenAIAPIKey mocks base method.
func (m *MockAgentPlatformService) UpdateOpenAIAPIKey(ctx context.Context, openaiApiKeyId string, openaiAPIKeyUpdate *godo.OpenAIAPIKeyUpdateRequest) (*godo.OpenAiApiKey, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOpenAIAPIKey", ctx, openaiApiKeyId, openaiAPIKeyUpdate)
	ret0, _ := ret[0].(*godo.OpenAiApiKey)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateOpenAIAPIKey indicates an expected call of UpdateOpenAIAPIKey.
func (mr *MockAgentPlatformServiceMockRecorder) UpdateOpenAIAPIKey(ctx, openaiApiKeyId, openaiAPIKeyUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOpenAIAPIKey", reflect.TypeOf((*MockAgentPlatformService)(nil).UpdateOpenAIAPIKey), ctx, openaiApiKeyId, openaiAPIKeyUpdate)
}

// UpdateScenarioSet mocks base method.
func (m *MockAgentPlatformService) UpdateScenarioSet(ctx context.Context, scenarioSetUUID string, updateRequest *godo.UpdateScenarioSetRequest) (*godo.ScenarioSet, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScenarioSet", ctx, scenarioSetUUID, updateRequest)
	ret0, _ := ret[0].(*godo.ScenarioSet)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateScenarioSet indicates an expected call of UpdateScenarioSet.
func (mr *MockAgentPlatformServiceMockRecorder) UpdateScenarioSet(ctx, scenarioSetUUID, updateRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScenarioSet", reflect.TypeOf((*MockAgentPlatformService)(nil).UpdateScenarioSet), ctx, scenarioSetUUID, updateRequest)
}

// UpdateSimulationRun mocks base method.
func (m *MockAgentPlatformService) UpdateSimulationRun(ctx context.Context, runUUID string, updateRequest *godo.UpdateSimulationRunRequest) (*godo.SimulationRun, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSimulationRun", ctx, runUUID, updateRequest)
	ret0, _ := ret[0].(*godo.SimulationRun)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateSimulationRun indicates an expected call of UpdateSimulationRun.
func (mr *MockAgentPlatformServiceMockRecorder) UpdateSimulationRun(ctx, runUUID, updateRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSimulationRun", reflect.TypeOf((*MockAgentPlatformService)(nil).UpdateSimulationRun), ctx, runUUID, updateRequest)
}
