// Code generated by MockGen. DO NOT EDIT.
// Source: mcp-digitalocean/pkg/registry/docs (interfaces: DocsService)
//
// Generated by this command:
//
//	mockgen -destination=./pkg/registry/docs/mocks.go -package docs mcp-digitalocean/pkg/registry/docs DocsService
//

// Package docs is a generated GoMock package.
package docs

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDocsService is a mock of DocsService interface.
type MockDocsService struct {
	ctrl     *gomock.Controller
	recorder *MockDocsServiceMockRecorder
	isgomock struct{}
}

// MockDocsServiceMockRecorder is the mock recorder for MockDocsService.
type MockDocsServiceMockRecorder struct {
	mock *MockDocsService
}

// NewMockDocsService creates a new mock instance.
func NewMockDocsService(ctrl *gomock.Controller) *MockDocsService {
	mock := &MockDocsService{ctrl: ctrl}
	mock.recorder = &MockDocsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocsService) EXPECT() *MockDocsServiceMockRecorder {
	return m.recorder
}

// ExtractRelatedLinks mocks base method.
func (m *MockDocsService) ExtractRelatedLinks(url string) ([]RelatedLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractRelatedLinks", url)
	ret0, _ := ret[0].([]RelatedLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractRelatedLinks indicates an expected call of ExtractRelatedLinks.
func (mr *MockDocsServiceMockRecorder) ExtractRelatedLinks(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractRelatedLinks", reflect.TypeOf((*MockDocsService)(nil).ExtractRelatedLinks), url)
}

// FetchDocPage mocks base method.
func (m *MockDocsService) FetchDocPage(url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDocPage", url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchDocPage indicates an expected call of FetchDocPage.
func (mr *MockDocsServiceMockRecorder) FetchDocPage(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDocPage", reflect.TypeOf((*MockDocsService)(nil).FetchDocPage), url)
}

// FindQuickstart mocks base method.
func (m *MockDocsService) FindQuickstart(service string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindQuickstart", service)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindQuickstart indicates an expected call of FindQuickstart.
func (mr *MockDocsServiceMockRecorder) FindQuickstart(service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindQuickstart", reflect.TypeOf((*MockDocsService)(nil).FindQuickstart), service)
}

// FindTroubleshootPage mocks base method.
func (m *MockDocsService) FindTroubleshootPage(symptom string) ([]DocsEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTroubleshootPage", symptom)
	ret0, _ := ret[0].([]DocsEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTroubleshootPage indicates an expected call of FindTroubleshootPage.
func (mr *MockDocsServiceMockRecorder) FindTroubleshootPage(symptom any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTroubleshootPage", reflect.TypeOf((*MockDocsService)(nil).FindTroubleshootPage), symptom)
}

// GetDocsIndex mocks base method.
func (m *MockDocsService) GetDocsIndex() (*DocsIndex, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDocsIndex")
	ret0, _ := ret[0].(*DocsIndex)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDocsIndex indicates an expected call of GetDocsIndex.
func (mr *MockDocsServiceMockRecorder) GetDocsIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDocsIndex", reflect.TypeOf((*MockDocsService)(nil).GetDocsIndex))
}

// GetLLMSIndexRecords mocks base method.
func (m *MockDocsService) GetLLMSIndexRecords() ([]LLMSIndexRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLLMSIndexRecords")
	ret0, _ := ret[0].([]LLMSIndexRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLLMSIndexRecords indicates an expected call of GetLLMSIndexRecords.
func (mr *MockDocsServiceMockRecorder) GetLLMSIndexRecords() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLLMSIndexRecords", reflect.TypeOf((*MockDocsService)(nil).GetLLMSIndexRecords))
}

// GetServiceIndex mocks base method.
func (m *MockDocsService) GetServiceIndex(service string) (*DocsIndex, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceIndex", service)
	ret0, _ := ret[0].(*DocsIndex)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceIndex indicates an expected call of GetServiceIndex.
func (mr *MockDocsServiceMockRecorder) GetServiceIndex(service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceIndex", reflect.TypeOf((*MockDocsService)(nil).GetServiceIndex), service)
}

// SemanticSearch mocks base method.
func (m *MockDocsService) SemanticSearch(ctx context.Context, query string, resultLimit int) ([]SemanticSearchHit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SemanticSearch", ctx, query, resultLimit)
	ret0, _ := ret[0].([]SemanticSearchHit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SemanticSearch indicates an expected call of SemanticSearch.
func (mr *MockDocsServiceMockRecorder) SemanticSearch(ctx, query, resultLimit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SemanticSearch", reflect.TypeOf((*MockDocsService)(nil).SemanticSearch), ctx, query, resultLimit)
}
