// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/digitalocean/godo (interfaces: SignalsService)
//
// Generated by this command:
//
//	mockgen -destination=./mocks.go -package signals github.com/digitalocean/godo SignalsService
//

// Package signals is a generated GoMock package.
package signals

import (
	context "context"
	reflect "reflect"

	godo "github.com/digitalocean/godo"
	gomock "go.uber.org/mock/gomock"
)

// MockSignalsService is a mock of SignalsService interface.
type MockSignalsService struct {
	ctrl     *gomock.Controller
	recorder *MockSignalsServiceMockRecorder
	isgomock struct{}
}

// MockSignalsServiceMockRecorder is the mock recorder for MockSignalsService.
type MockSignalsServiceMockRecorder struct {
	mock *MockSignalsService
}

// NewMockSignalsService creates a new mock instance.
func NewMockSignalsService(ctrl *gomock.Controller) *MockSignalsService {
	mock := &MockSignalsService{ctrl: ctrl}
	mock.recorder = &MockSignalsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignalsService) EXPECT() *MockSignalsServiceMockRecorder {
	return m.recorder
}

// GetAgentConsent mocks base method.
func (m *MockSignalsService) GetAgentConsent(arg0 context.Context, arg1 string) (*godo.SignalsAgentConsent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentConsent", arg0, arg1)
	ret0, _ := ret[0].(*godo.SignalsAgentConsent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAgentConsent indicates an expected call of GetAgentConsent.
func (mr *MockSignalsServiceMockRecorder) GetAgentConsent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentConsent", reflect.TypeOf((*MockSignalsService)(nil).GetAgentConsent), arg0, arg1)
}

// GetExport mocks base method.
func (m *MockSignalsService) GetExport(arg0 context.Context, arg1 string) (*godo.SignalsExportJob, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExport", arg0, arg1)
	ret0, _ := ret[0].(*godo.SignalsExportJob)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetExport indicates an expected call of GetExport.
func (mr *MockSignalsServiceMockRecorder) GetExport(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExport", reflect.TypeOf((*MockSignalsService)(nil).GetExport), arg0, arg1)
}

// GetExportDownload mocks base method.
func (m *MockSignalsService) GetExportDownload(arg0 context.Context, arg1 string) (*godo.SignalsExportDownload, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExportDownload", arg0, arg1)
	ret0, _ := ret[0].(*godo.SignalsExportDownload)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetExportDownload indicates an expected call of GetExportDownload.
func (mr *MockSignalsServiceMockRecorder) GetExportDownload(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExportDownload", reflect.TypeOf((*MockSignalsService)(nil).GetExportDownload), arg0, arg1)
}

// GetExportOptions mocks base method.
func (m *MockSignalsService) GetExportOptions(arg0 context.Context) (*godo.SignalsExportOptions, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExportOptions", arg0)
	ret0, _ := ret[0].(*godo.SignalsExportOptions)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetExportOptions indicates an expected call of GetExportOptions.
func (mr *MockSignalsServiceMockRecorder) GetExportOptions(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExportOptions", reflect.TypeOf((*MockSignalsService)(nil).GetExportOptions), arg0)
}

// GetSegment mocks base method.
func (m *MockSignalsService) GetSegment(arg0 context.Context, arg1 string, arg2 *godo.SignalsCursorPageOptions) (*godo.SignalsSegmentDetailResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSegment", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.SignalsSegmentDetailResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSegment indicates an expected call of GetSegment.
func (mr *MockSignalsServiceMockRecorder) GetSegment(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSegment", reflect.TypeOf((*MockSignalsService)(nil).GetSegment), arg0, arg1, arg2)
}

// GetSegmentSignalReport mocks base method.
func (m *MockSignalsService) GetSegmentSignalReport(arg0 context.Context, arg1 string) (*godo.SignalsReport, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSegmentSignalReport", arg0, arg1)
	ret0, _ := ret[0].(*godo.SignalsReport)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSegmentSignalReport indicates an expected call of GetSegmentSignalReport.
func (mr *MockSignalsServiceMockRecorder) GetSegmentSignalReport(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSegmentSignalReport", reflect.TypeOf((*MockSignalsService)(nil).GetSegmentSignalReport), arg0, arg1)
}

// ListAgentSessions mocks base method.
func (m *MockSignalsService) ListAgentSessions(arg0 context.Context, arg1 string, arg2 *godo.SignalsListAgentSessionsOptions) (*godo.SignalsListAgentSessionsResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgentSessions", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.SignalsListAgentSessionsResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAgentSessions indicates an expected call of ListAgentSessions.
func (mr *MockSignalsServiceMockRecorder) ListAgentSessions(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgentSessions", reflect.TypeOf((*MockSignalsService)(nil).ListAgentSessions), arg0, arg1, arg2)
}

// ListExports mocks base method.
func (m *MockSignalsService) ListExports(arg0 context.Context, arg1 *godo.SignalsListExportsOptions) (*godo.SignalsListExportsResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExports", arg0, arg1)
	ret0, _ := ret[0].(*godo.SignalsListExportsResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListExports indicates an expected call of ListExports.
func (mr *MockSignalsServiceMockRecorder) ListExports(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExports", reflect.TypeOf((*MockSignalsService)(nil).ListExports), arg0, arg1)
}

// ListSessionDialogues mocks base method.
func (m *MockSignalsService) ListSessionDialogues(arg0 context.Context, arg1 string, arg2 *godo.SignalsListDialoguesOptions) (*godo.SignalsSessionDialoguesResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessionDialogues", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.SignalsSessionDialoguesResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSessionDialogues indicates an expected call of ListSessionDialogues.
func (mr *MockSignalsServiceMockRecorder) ListSessionDialogues(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessionDialogues", reflect.TypeOf((*MockSignalsService)(nil).ListSessionDialogues), arg0, arg1, arg2)
}

// ListSessionSegments mocks base method.
func (m *MockSignalsService) ListSessionSegments(arg0 context.Context, arg1 string, arg2 *godo.SignalsListSegmentsOptions) (*godo.SignalsListSegmentsResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessionSegments", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.SignalsListSegmentsResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSessionSegments indicates an expected call of ListSessionSegments.
func (mr *MockSignalsServiceMockRecorder) ListSessionSegments(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessionSegments", reflect.TypeOf((*MockSignalsService)(nil).ListSessionSegments), arg0, arg1, arg2)
}

// SetAgentConsent mocks base method.
func (m *MockSignalsService) SetAgentConsent(arg0 context.Context, arg1 string, arg2 bool) (*godo.SignalsConsentRecord, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAgentConsent", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.SignalsConsentRecord)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SetAgentConsent indicates an expected call of SetAgentConsent.
func (mr *MockSignalsServiceMockRecorder) SetAgentConsent(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAgentConsent", reflect.TypeOf((*MockSignalsService)(nil).SetAgentConsent), arg0, arg1, arg2)
}
