// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/digitalocean/godo (interfaces: VectorDBsService)
//
// Generated by this command:
//
//	mockgen -destination=./mocks.go -package vectordb github.com/digitalocean/godo VectorDBsService
//

// Package vectordb is a generated GoMock package.
package vectordb

import (
	context "context"
	reflect "reflect"

	godo "github.com/digitalocean/godo"
	gomock "go.uber.org/mock/gomock"
)

// MockVectorDBsService is a mock of VectorDBsService interface.
type MockVectorDBsService struct {
	ctrl     *gomock.Controller
	recorder *MockVectorDBsServiceMockRecorder
	isgomock struct{}
}

// MockVectorDBsServiceMockRecorder is the mock recorder for MockVectorDBsService.
type MockVectorDBsServiceMockRecorder struct {
	mock *MockVectorDBsService
}

// NewMockVectorDBsService creates a new mock instance.
func NewMockVectorDBsService(ctrl *gomock.Controller) *MockVectorDBsService {
	mock := &MockVectorDBsService{ctrl: ctrl}
	mock.recorder = &MockVectorDBsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVectorDBsService) EXPECT() *MockVectorDBsServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVectorDBsService) Create(arg0 context.Context, arg1 *godo.VectorDBCreateRequest) (*godo.VectorDB, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*godo.VectorDB)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create indicates an expected call of Create.
func (mr *MockVectorDBsServiceMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVectorDBsService)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockVectorDBsService) Delete(arg0 context.Context, arg1 string) (*godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*godo.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockVectorDBsServiceMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVectorDBsService)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockVectorDBsService) Get(arg0 context.Context, arg1 string) (*godo.VectorDB, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*godo.VectorDB)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockVectorDBsServiceMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVectorDBsService)(nil).Get), arg0, arg1)
}

// GetCredentials mocks base method.
func (m *MockVectorDBsService) GetCredentials(arg0 context.Context, arg1 string) (*godo.VectorDBAdminCredentials, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentials", arg0, arg1)
	ret0, _ := ret[0].(*godo.VectorDBAdminCredentials)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCredentials indicates an expected call of GetCredentials.
func (mr *MockVectorDBsServiceMockRecorder) GetCredentials(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentials", reflect.TypeOf((*MockVectorDBsService)(nil).GetCredentials), arg0, arg1)
}

// GetRestoreStatus mocks base method.
func (m *MockVectorDBsService) GetRestoreStatus(arg0 context.Context, arg1, arg2 string) (*godo.VectorDBRestoreStatus, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRestoreStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.VectorDBRestoreStatus)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRestoreStatus indicates an expected call of GetRestoreStatus.
func (mr *MockVectorDBsServiceMockRecorder) GetRestoreStatus(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestoreStatus", reflect.TypeOf((*MockVectorDBsService)(nil).GetRestoreStatus), arg0, arg1, arg2)
}

// List mocks base method.
func (m *MockVectorDBsService) List(arg0 context.Context, arg1 *godo.ListOptions) ([]godo.VectorDB, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]godo.VectorDB)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockVectorDBsServiceMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVectorDBsService)(nil).List), arg0, arg1)
}

// ListBackups mocks base method.
func (m *MockVectorDBsService) ListBackups(arg0 context.Context, arg1 string) ([]godo.VectorDBBackup, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBackups", arg0, arg1)
	ret0, _ := ret[0].([]godo.VectorDBBackup)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBackups indicates an expected call of ListBackups.
func (mr *MockVectorDBsServiceMockRecorder) ListBackups(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBackups", reflect.TypeOf((*MockVectorDBsService)(nil).ListBackups), arg0, arg1)
}

// Resize mocks base method.
func (m *MockVectorDBsService) Resize(arg0 context.Context, arg1 string, arg2 *godo.VectorDBResizeRequest) (*godo.VectorDB, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resize", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.VectorDB)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Resize indicates an expected call of Resize.
func (mr *MockVectorDBsServiceMockRecorder) Resize(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resize", reflect.TypeOf((*MockVectorDBsService)(nil).Resize), arg0, arg1, arg2)
}

// RestoreBackup mocks base method.
func (m *MockVectorDBsService) RestoreBackup(arg0 context.Context, arg1, arg2 string, arg3 *godo.VectorDBRestoreBackupRequest) (*godo.VectorDBRestoreBackupResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreBackup", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*godo.VectorDBRestoreBackupResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RestoreBackup indicates an expected call of RestoreBackup.
func (mr *MockVectorDBsServiceMockRecorder) RestoreBackup(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreBackup", reflect.TypeOf((*MockVectorDBsService)(nil).RestoreBackup), arg0, arg1, arg2, arg3)
}

// Update mocks base method.
func (m *MockVectorDBsService) Update(arg0 context.Context, arg1 string, arg2 *godo.VectorDBUpdateRequest) (*godo.VectorDB, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.VectorDB)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Update indicates an expected call of Update.
func (mr *MockVectorDBsServiceMockRecorder) Update(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVectorDBsService)(nil).Update), arg0, arg1, arg2)
}

// UpdateTags mocks base method.
func (m *MockVectorDBsService) UpdateTags(arg0 context.Context, arg1 string, arg2 *godo.VectorDBUpdateTagsRequest) (*godo.VectorDB, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTags", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.VectorDB)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateTags indicates an expected call of UpdateTags.
func (mr *MockVectorDBsServiceMockRecorder) UpdateTags(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTags", reflect.TypeOf((*MockVectorDBsService)(nil).UpdateTags), arg0, arg1, arg2)
}
